version: '3.8'

services:
  django:
    container_name: webb
    build: 
      context: ./dcelery
    command: python manage.py runserver 0.0.0.0:8000 
    volumes: 
      - ./dcelery:/usr/src/app/ # ?
    ports:
      - 8001:8000 # ?
    environment:
    - DEBUG=1
    - SECRET_KEY=rett

    